### PR TITLE
Fixed the Error in the Form1.cs

### PR DESCRIPTION
**Pull request by fml508**
### Long story short the Form1.cs DirectoryPath variable was way off. (back 3 folders, and forward 1 off.)
Fixed it, all good **[for now]**

_Before:_
`string directoryPath = Application.StartupPath;`

_After:_
`string directoryPath = Path.Combine(Application.StartupPath, "..", "..", "..", "QRcodes");`

I know it's ugly but functional. #2

### CODE REVIEW

**Review by thetruekys — COMMENTED** [review]
As they say.. **YAY**

(and yes please god fix that triple ".." thing.)

**Review by thetruekys — COMMENTED** [review]
Well Done

**Review by fml508 — COMMENTED** [review]
gg

**Review by fml508 — COMMENTED** [review]
all good.

**Pull request merged**
